### ISSUE TITLE
Beacon-detection without location permission

### ISSUE THREAD

**Issue by albo1337** [frostney/react-native-ibeacon#29]
Is it possible to detect Beacons without location permission? I think we just need bluetooth to detect beacons and not location permission.

Kind regards,
albo1337

**Comment by frostney** [comment]
The problem here is that the iBeacon functionality in the iOS SDK is bundled with `CoreLocation`. `CoreLocation` needs location permission, in order to use any of its API methods.

If you were to disable location permissions, you would not be able to get the location updates (ranging, scanning) for the beacons.

**Comment by albo1337** [comment]
Damn! Ok, thanks a lot for that quick answer.

**Comment by albo1337** [comment]
Then I have another problem which is similar to this one (this time to check for location):

https://github.com/frostney/react-native-bluetooth-state/issues/3
